version: '3'
services:

  # PHP Service
  app:
    build:
      args:
        user: bms-del087
        uid: 1000
      context: ./php
      dockerfile: php5.4-fpm.dockerfile
    image: rb/php-fpm:5.4
    restart: unless-stopped
    ports:
    - '${FORWARD_FPM_PORT:-9001}:9000'
    tty: true
    environment:
      TZ: '${TZ:-Asia/Jakarta}'
    volumes:
      - './${APP_DOCROOT}:/var/www'
    working_dir: /var/www
    networks:
      - rbnet

  # Nginx Service
  webserver:
    image:  nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - '${FORWARD_APP_PORT:-80}:80'
    volumes:
      - './${APP_DOCROOT}:/var/www'
      - './nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - rbnet

# Docker networks
networks:
  rbnet:
    name: rbnet
    driver: bridge
