<?php


class FormatMsg {
	public static function echoTest(){
		$msg = array(
			"0" => "ECHO*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN",
			"1" => "ECHO*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*STATUS*KETERANGAN*MSGBROADCAST",
		);
		return $msg;
    }	
	public static function signOn(){
		$msg = array(
			"0" => "SIGNON*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*STATUS*KETERANGAN*MSGBROADCAST*SETTING",
			"1" => "SIGNON*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*STATUS*KETERANGAN*MSGBROADCAST*SETTING",
		);
		return $msg;
    }
	public static function signOff(){
		$msg = array(
			"0" => "SIGNOFF*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN",
			"1" => "SIGNOFF*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*STATUS*KETERANGAN*MSGBROADCAST",
		);
		return $msg;
	}
	public static function pajakSolo(){
		$msg = "SWITCHERID*BILLERCODE*CUSTOMERID*BILLQUANTITY*NOREF1*NOREF2*NTP*NTB*KODE_PEMDA*NOP*KODE_PAJAK*TAHUN_PAJAK*NAMA*LOKASI*KELURAHAN*KECAMATAN*PROVINSI*LUAS_TANAH*LUAS_BANGUNAN*TANGGAL_JTH_TEMPO*TAGIHAN*DENDA*TOTAL_BAYAR";
		return $msg;
	}
	public static function pkb(){
            $msg = "KND_ID*KND_NOPOL*KND_DF_JENIS*KND_NAMA*KND_DF_NOMOR*KND_DF_TANGGAL*KND_DF_JAM*KND_DF_PROSES*USR_FULL_NAME*KND_KOHIR*KND_SKUM*KND_ALAMAT*KEL_DESC*KEC_DESC*KAB_DESC*TPE_DESC*KD_MERK*MRK_DESC*JNS_DESC*KND_THN_BUAT*KND_CYL*KND_WARNA*KND_RANGKA*KND_MESIN*KND_NO_BPKB*KND_SD_NOTICE*KND_TGL_STNK*KND_SD_STNK*KD_BBM*BBM_DESC*WRN_DESC*KND_NOPOL_EKS*KND_JBB_PENUMPANG*KND_BERAT_KB*KND_JML_SUMBU_AS*KD_KAB*KD_JENIS*KD_TIPE*BOBOT*NILAI_JUAL*DASAR_PKB*KD_GOL*GOL_DESC*TGLBERLAKU*POKOK_NEW*POKOK_OLD*DENDA_NEW*DENDA_OLD*KND_MILIK_KE*KD_KEC*KD_KEL*KD_GUNA*KND_BLOKIR*KND_TGL_FAKTUR*KND_TGL_KUWITANSI*KND_BLOKIR_TGL*KND_BLOKIR_DESC*DRV_DESC*BILL_QUANTITY*REFF_NUM*ROW_ID*PTP_TANGGAL*NOM_PKB*JASARAHARJA*DENDA_NOM_PKB*DENDA_JASARAHARJA*NOM_PKB_TG*JASARAHARJA_TG*DENDA_NOM_PKB_TG*DENDA_JASARAHARJA_TG";
            return $msg;
        }
	public static function kai(){
		$msg = array(
			"NKAISCH" 		=> "ERRCODE*ERRMSG*ORG*DES*DEPDATE*ARVDATE*SCHEDULE*TRAINNO*CLASS*SUBCLASS*NUMPAXADULT*NUMPAXCHILD*NUMPAXINFANT*ADULTNAME1*ADULTBIRTHDATE1*ADULTMOBILE1*ADULTIDNO1*ADULTNAME2*ADULTBIRTHDATE2*ADULTMOBILE2*ADULTIDNO2*ADULTNAME3*ADULTBIRTHDATE3*ADULTMOBILE3*ADULTIDNO3*ADULTNAME4*ADULTBIRTHDATE4*ADULTMOBILE4*ADULTIDNO4*CHILDNAME1*CHILDBIRTHDATE1*CHILDNAME2*CHILDBIRTHDATE2*CHILDNAME3*CHILDBIRTHDATE3*CHILDNAME4*CHILDBIRTHDATE4*INFANTNAME1*INFANTBIRTHDATE1*INFANTNAME2*INFANTBIRTHDATE2*INFANTNAME3*INFANTBIRTHDATE3*INFANTNAME4*INFANTBIRTHDATE4*CALLER*NUMCODE*BOOKCODE*SEAT*NORMALSALES*EXTRAFEE*BOOKBALANCE*SEATMAPNULL*WAGONCODE*WAGONNO*WAGONCODE1*WAGONNO1*SEATROW1*SEATCOL1*WAGONCODE2*WAGONNO2*SEATROW2*SEATCOL2*WAGONCODE3*WAGONNO3*SEATROW3*SEATCOL3*WAGONCODE4*WAGONNO4*SEATROW4*SEATCOL4*CANCELREASON*STATUSCANCEL*REFUND*PAYTYPE*ROUTE*PAX*PAXNUM*REVENUE*TRAINNAME*ORIGINATION*DEPTIME*DESTINATION*ARVTIME*SEATNUMBER*PRICEADULT*PRICECHILD*PRICEINFANT",
			"NKAIBOO" 		=> "ERRCODE*ERRMSG*ORG*DES*DEPDATE*ARVDATE*SCHEDULE*TRAINNO*CLASS*SUBCLASS*NUMPAXADULT*NUMPAXCHILD*NUMPAXINFANT*ADULTNAME1*ADULTBIRTHDATE1*ADULTMOBILE1*ADULTIDNO1*ADULTNAME2*ADULTBIRTHDATE2*ADULTMOBILE2*ADULTIDNO2*ADULTNAME3*ADULTBIRTHDATE3*ADULTMOBILE3*ADULTIDNO3*ADULTNAME4*ADULTBIRTHDATE4*ADULTMOBILE4*ADULTIDNO4*CHILDNAME1*CHILDBIRTHDATE1*CHILDNAME2*CHILDBIRTHDATE2*CHILDNAME3*CHILDBIRTHDATE3*CHILDNAME4*CHILDBIRTHDATE4*INFANTNAME1*INFANTBIRTHDATE1*INFANTNAME2*INFANTBIRTHDATE2*INFANTNAME3*INFANTBIRTHDATE3*INFANTNAME4*INFANTBIRTHDATE4*CALLER*NUMCODE*BOOKCODE*SEAT*NORMALSALES*EXTRAFEE*BOOKBALANCE*SEATMAPNULL*WAGONCODE*WAGONNO*WAGONCODE1*WAGONNO1*SEATROW1*SEATCOL1*WAGONCODE2*WAGONNO2*SEATROW2*SEATCOL2*WAGONCODE3*WAGONNO3*SEATROW3*SEATCOL3*WAGONCODE4*WAGONNO4*SEATROW4*SEATCOL4*CANCELREASON*STATUSCANCEL*REFUND*PAYTYPE*ROUTE*PAX*PAXNUM*REVENUE*TRAINNAME*ORIGINATION*DEPTIME*DESTINATION*ARVTIME*SEATNUMBER*PRICEADULT*PRICECHILD*PRICEINFANT",
			"NKAIBOOK" 		=> "ERRCODE*ERRMSG*ORG*DES*DEPDATE*ARVDATE*SCHEDULE*TRAINNO*CLASS*SUBCLASS*NUMPAXADULT*NUMPAXCHILD*NUMPAXINFANT*ADULTNAME1*ADULTBIRTHDATE1*ADULTMOBILE1*ADULTIDNO1*ADULTNAME2*ADULTBIRTHDATE2*ADULTMOBILE2*ADULTIDNO2*ADULTNAME3*ADULTBIRTHDATE3*ADULTMOBILE3*ADULTIDNO3*ADULTNAME4*ADULTBIRTHDATE4*ADULTMOBILE4*ADULTIDNO4*CHILDNAME1*CHILDBIRTHDATE1*CHILDNAME2*CHILDBIRTHDATE2*CHILDNAME3*CHILDBIRTHDATE3*CHILDNAME4*CHILDBIRTHDATE4*INFANTNAME1*INFANTBIRTHDATE1*INFANTNAME2*INFANTBIRTHDATE2*INFANTNAME3*INFANTBIRTHDATE3*INFANTNAME4*INFANTBIRTHDATE4*CALLER*NUMCODE*BOOKCODE*SEAT*NORMALSALES*EXTRAFEE*BOOKBALANCE*SEATMAPNULL*WAGONCODE*WAGONNO*WAGONCODE1*WAGONNO1*SEATROW1*SEATCOL1*WAGONCODE2*WAGONNO2*SEATROW2*SEATCOL2*WAGONCODE3*WAGONNO3*SEATROW3*SEATCOL3*WAGONCODE4*WAGONNO4*SEATROW4*SEATCOL4*CANCELREASON*STATUSCANCEL*REFUND*PAYTYPE*ROUTE*PAX*PAXNUM*REVENUE*TRAINNAME*ORIGINATION*DEPTIME*DESTINATION*ARVTIME*SEATNUMBER*PRICEADULT*PRICECHILD*PRICEINFANT",
			"NKAIUPD" 		=> "ERRCODE*ERRMSG*ORG*DES*DEPDATE*ARVDATE*SCHEDULE*TRAINNO*CLASS*SUBCLASS*NUMPAXADULT*NUMPAXCHILD*NUMPAXINFANT*ADULTNAME1*ADULTBIRTHDATE1*ADULTMOBILE1*ADULTIDNO1*ADULTNAME2*ADULTBIRTHDATE2*ADULTMOBILE2*ADULTIDNO2*ADULTNAME3*ADULTBIRTHDATE3*ADULTMOBILE3*ADULTIDNO3*ADULTNAME4*ADULTBIRTHDATE4*ADULTMOBILE4*ADULTIDNO4*CHILDNAME1*CHILDBIRTHDATE1*CHILDNAME2*CHILDBIRTHDATE2*CHILDNAME3*CHILDBIRTHDATE3*CHILDNAME4*CHILDBIRTHDATE4*INFANTNAME1*INFANTBIRTHDATE1*INFANTNAME2*INFANTBIRTHDATE2*INFANTNAME3*INFANTBIRTHDATE3*INFANTNAME4*INFANTBIRTHDATE4*CALLER*NUMCODE*BOOKCODE*SEAT*NORMALSALES*EXTRAFEE*BOOKBALANCE*SEATMAPNULL*WAGONCODE*WAGONNO*WAGONCODE1*WAGONNO1*SEATROW1*SEATCOL1*WAGONCODE2*WAGONNO2*SEATROW2*SEATCOL2*WAGONCODE3*WAGONNO3*SEATROW3*SEATCOL3*WAGONCODE4*WAGONNO4*SEATROW4*SEATCOL4*CANCELREASON*STATUSCANCEL*REFUND*PAYTYPE*ROUTE*PAX*PAXNUM*REVENUE*TRAINNAME*ORIGINATION*DEPTIME*DESTINATION*ARVTIME*SEATNUMBER*PRICEADULT*PRICECHILD*PRICEINFANT",
			"NKAICAN" 		=> "ERRCODE*ERRMSG*ORG*DES*DEPDATE*ARVDATE*SCHEDULE*TRAINNO*CLASS*SUBCLASS*NUMPAXADULT*NUMPAXCHILD*NUMPAXINFANT*ADULTNAME1*ADULTBIRTHDATE1*ADULTMOBILE1*ADULTIDNO1*ADULTNAME2*ADULTBIRTHDATE2*ADULTMOBILE2*ADULTIDNO2*ADULTNAME3*ADULTBIRTHDATE3*ADULTMOBILE3*ADULTIDNO3*ADULTNAME4*ADULTBIRTHDATE4*ADULTMOBILE4*ADULTIDNO4*CHILDNAME1*CHILDBIRTHDATE1*CHILDNAME2*CHILDBIRTHDATE2*CHILDNAME3*CHILDBIRTHDATE3*CHILDNAME4*CHILDBIRTHDATE4*INFANTNAME1*INFANTBIRTHDATE1*INFANTNAME2*INFANTBIRTHDATE2*INFANTNAME3*INFANTBIRTHDATE3*INFANTNAME4*INFANTBIRTHDATE4*CALLER*NUMCODE*BOOKCODE*SEAT*NORMALSALES*EXTRAFEE*BOOKBALANCE*SEATMAPNULL*WAGONCODE*WAGONNO*WAGONCODE1*WAGONNO1*SEATROW1*SEATCOL1*WAGONCODE2*WAGONNO2*SEATROW2*SEATCOL2*WAGONCODE3*WAGONNO3*SEATROW3*SEATCOL3*WAGONCODE4*WAGONNO4*SEATROW4*SEATCOL4*CANCELREASON*STATUSCANCEL*REFUND*PAYTYPE*ROUTE*PAX*PAXNUM*REVENUE*TRAINNAME*ORIGINATION*DEPTIME*DESTINATION*ARVTIME*SEATNUMBER*PRICEADULT*PRICECHILD*PRICEINFANT",
			"NKAIMAP" 		=> "ERRCODE*ERRMSG*ORG*DES*DEPDATE*ARVDATE*SCHEDULE*TRAINNO*CLASS*SUBCLASS*NUMPAXADULT*NUMPAXCHILD*NUMPAXINFANT*ADULTNAME1*ADULTBIRTHDATE1*ADULTMOBILE1*ADULTIDNO1*ADULTNAME2*ADULTBIRTHDATE2*ADULTMOBILE2*ADULTIDNO2*ADULTNAME3*ADULTBIRTHDATE3*ADULTMOBILE3*ADULTIDNO3*ADULTNAME4*ADULTBIRTHDATE4*ADULTMOBILE4*ADULTIDNO4*CHILDNAME1*CHILDBIRTHDATE1*CHILDNAME2*CHILDBIRTHDATE2*CHILDNAME3*CHILDBIRTHDATE3*CHILDNAME4*CHILDBIRTHDATE4*INFANTNAME1*INFANTBIRTHDATE1*INFANTNAME2*INFANTBIRTHDATE2*INFANTNAME3*INFANTBIRTHDATE3*INFANTNAME4*INFANTBIRTHDATE4*CALLER*NUMCODE*BOOKCODE*SEAT*NORMALSALES*EXTRAFEE*BOOKBALANCE*SEATMAPNULL*WAGONCODE*WAGONNO*WAGONCODE1*WAGONNO1*SEATROW1*SEATCOL1*WAGONCODE2*WAGONNO2*SEATROW2*SEATCOL2*WAGONCODE3*WAGONNO3*SEATROW3*SEATCOL3*WAGONCODE4*WAGONNO4*SEATROW4*SEATCOL4*CANCELREASON*STATUSCANCEL*REFUND*PAYTYPE*ROUTE*PAX*PAXNUM*REVENUE*TRAINNAME*ORIGINATION*DEPTIME*DESTINATION*ARVTIME*SEATNUMBER*PRICEADULT*PRICECHILD*PRICEINFANT",
			"NKAISEAT" 		=> "ERRCODE*ERRMSG*ORG*DES*DEPDATE*ARVDATE*SCHEDULE*TRAINNO*CLASS*SUBCLASS*NUMPAXADULT*NUMPAXCHILD*NUMPAXINFANT*ADULTNAME1*ADULTBIRTHDATE1*ADULTMOBILE1*ADULTIDNO1*ADULTNAME2*ADULTBIRTHDATE2*ADULTMOBILE2*ADULTIDNO2*ADULTNAME3*ADULTBIRTHDATE3*ADULTMOBILE3*ADULTIDNO3*ADULTNAME4*ADULTBIRTHDATE4*ADULTMOBILE4*ADULTIDNO4*CHILDNAME1*CHILDBIRTHDATE1*CHILDNAME2*CHILDBIRTHDATE2*CHILDNAME3*CHILDBIRTHDATE3*CHILDNAME4*CHILDBIRTHDATE4*INFANTNAME1*INFANTBIRTHDATE1*INFANTNAME2*INFANTBIRTHDATE2*INFANTNAME3*INFANTBIRTHDATE3*INFANTNAME4*INFANTBIRTHDATE4*CALLER*NUMCODE*BOOKCODE*SEAT*NORMALSALES*EXTRAFEE*BOOKBALANCE*SEATMAPNULL*WAGONCODE*WAGONNO*WAGONCODE1*WAGONNO1*SEATROW1*SEATCOL1*WAGONCODE2*WAGONNO2*SEATROW2*SEATCOL2*WAGONCODE3*WAGONNO3*SEATROW3*SEATCOL3*WAGONCODE4*WAGONNO4*SEATROW4*SEATCOL4*CANCELREASON*STATUSCANCEL*REFUND*PAYTYPE*ROUTE*PAX*PAXNUM*REVENUE*TRAINNAME*ORIGINATION*DEPTIME*DESTINATION*ARVTIME*SEATNUMBER*PRICEADULT*PRICECHILD*PRICEINFANT",
			"NKAIPAY" 		=> "ERRCODE*ERRMSG*ORG*DES*DEPDATE*ARVDATE*SCHEDULE*TRAINNO*CLASS*SUBCLASS*NUMPAXADULT*NUMPAXCHILD*NUMPAXINFANT*ADULTNAME1*ADULTBIRTHDATE1*ADULTMOBILE1*ADULTIDNO1*ADULTNAME2*ADULTBIRTHDATE2*ADULTMOBILE2*ADULTIDNO2*ADULTNAME3*ADULTBIRTHDATE3*ADULTMOBILE3*ADULTIDNO3*ADULTNAME4*ADULTBIRTHDATE4*ADULTMOBILE4*ADULTIDNO4*CHILDNAME1*CHILDBIRTHDATE1*CHILDNAME2*CHILDBIRTHDATE2*CHILDNAME3*CHILDBIRTHDATE3*CHILDNAME4*CHILDBIRTHDATE4*INFANTNAME1*INFANTBIRTHDATE1*INFANTNAME2*INFANTBIRTHDATE2*INFANTNAME3*INFANTBIRTHDATE3*INFANTNAME4*INFANTBIRTHDATE4*CALLER*NUMCODE*BOOKCODE*SEAT*NORMALSALES*EXTRAFEE*BOOKBALANCE*SEATMAPNULL*WAGONCODE*WAGONNO*WAGONCODE1*WAGONNO1*SEATROW1*SEATCOL1*WAGONCODE2*WAGONNO2*SEATROW2*SEATCOL2*WAGONCODE3*WAGONNO3*SEATROW3*SEATCOL3*WAGONCODE4*WAGONNO4*SEATROW4*SEATCOL4*CANCELREASON*STATUSCANCEL*REFUND*PAYTYPE*ROUTE*PAX*PAXNUM*REVENUE*TRAINNAME*ORIGINATION*DEPTIME*DESTINATION*ARVTIME*SEATNUMBER*PRICEADULT*PRICECHILD*PRICEINFANT",
			"NKAIBOKINF"	=> "ERRCODE*ERRMSG*ORG*DES*DEPDATE*ARVDATE*SCHEDULE*TRAINNO*CLASS*SUBCLASS*NUMPAXADULT*NUMPAXCHILD*NUMPAXINFANT*ADULTNAME1*ADULTBIRTHDATE1*ADULTMOBILE1*ADULTIDNO1*ADULTNAME2*ADULTBIRTHDATE2*ADULTMOBILE2*ADULTIDNO2*ADULTNAME3*ADULTBIRTHDATE3*ADULTMOBILE3*ADULTIDNO3*ADULTNAME4*ADULTBIRTHDATE4*ADULTMOBILE4*ADULTIDNO4*CHILDNAME1*CHILDBIRTHDATE1*CHILDNAME2*CHILDBIRTHDATE2*CHILDNAME3*CHILDBIRTHDATE3*CHILDNAME4*CHILDBIRTHDATE4*INFANTNAME1*INFANTBIRTHDATE1*INFANTNAME2*INFANTBIRTHDATE2*INFANTNAME3*INFANTBIRTHDATE3*INFANTNAME4*INFANTBIRTHDATE4*CALLER*NUMCODE*BOOKCODE*SEAT*NORMALSALES*EXTRAFEE*BOOKBALANCE*SEATMAPNULL*WAGONCODE*WAGONNO*WAGONCODE1*WAGONNO1*SEATROW1*SEATCOL1*WAGONCODE2*WAGONNO2*SEATROW2*SEATCOL2*WAGONCODE3*WAGONNO3*SEATROW3*SEATCOL3*WAGONCODE4*WAGONNO4*SEATROW4*SEATCOL4*CANCELREASON*STATUSCANCEL*REFUND*PAYTYPE*ROUTE*PAX*PAXNUM*REVENUE*TRAINNAME*ORIGINATION*DEPTIME*DESTINATION*ARVTIME*SEATNUMBER*PRICEADULT*PRICECHILD*PRICEINFANT",
			"NKAIGPAY"  	=> "ERRCODE*ERRMSG*ORG*DES*DEPDATE*ARVDATE*SCHEDULE*TRAINNO*CLASS*SUBCLASS*NUMPAXADULT*NUMPAXCHILD*NUMPAXINFANT*ADULTNAME1*ADULTBIRTHDATE1*ADULTMOBILE1*ADULTIDNO1*ADULTNAME2*ADULTBIRTHDATE2*ADULTMOBILE2*ADULTIDNO2*ADULTNAME3*ADULTBIRTHDATE3*ADULTMOBILE3*ADULTIDNO3*ADULTNAME4*ADULTBIRTHDATE4*ADULTMOBILE4*ADULTIDNO4*CHILDNAME1*CHILDBIRTHDATE1*CHILDNAME2*CHILDBIRTHDATE2*CHILDNAME3*CHILDBIRTHDATE3*CHILDNAME4*CHILDBIRTHDATE4*INFANTNAME1*INFANTBIRTHDATE1*INFANTNAME2*INFANTBIRTHDATE2*INFANTNAME3*INFANTBIRTHDATE3*INFANTNAME4*INFANTBIRTHDATE4*CALLER*NUMCODE*BOOKCODE*SEAT*NORMALSALES*EXTRAFEE*BOOKBALANCE*SEATMAPNULL*WAGONCODE*WAGONNO*WAGONCODE1*WAGONNO1*SEATROW1*SEATCOL1*WAGONCODE2*WAGONNO2*SEATROW2*SEATCOL2*WAGONCODE3*WAGONNO3*SEATROW3*SEATCOL3*WAGONCODE4*WAGONNO4*SEATROW4*SEATCOL4*CANCELREASON*STATUSCANCEL*REFUND*PAYTYPE*ROUTE*PAX*PAXNUM*REVENUE*TRAINNAME*ORIGINATION*DEPTIME*DESTINATION*ARVTIME*SEATNUMBER*PRICEADULT*PRICECHILD*PRICEINFANT",
		);
		return $msg;
	}
	public static function cekSaldo(){
        $msg = array(
			"0" => "SAL*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN",
			"1" => "SAL*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*STATUS*KETERANGAN",
		);
		return $msg;
    }
	public static function deposit(){
		$msg = array(
			"0" => "TIKET*KDPRODUK*MID*STEP*TANGGAL*VIA*BANK*NOMINAL*IDOUTLET*PIN*TOKEN",
			"1" => "TIKET*KDPRODUK*MID*STEP*TANGGAL*VIA*BANK*NOMINAL*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*STATUS*KETERANGAN",
		);
		return $msg;
	}
	public static function gantiPin(){
		$msg = array(
			"0" => "GPIN*KDPRODUK*MID*STEP*TANGGAL*VIA*PINBARU*IDOUTLET*PIN*TOKEN",
			"1" => "GPIN*KDPRODUK*MID*STEP*TANGGAL*VIA*PINBARU*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*STATUS*KETERANGAN",
		);
		return $msg;
	}
	public static function cekKomisi(){
		$msg = array(
			"0" => "BONUS*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN",
			"1" => "BONUS*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*STATUS*KETERANGAN",
		);
		return $msg;
	}
	public static function komplain(){
		$msg = array(
			"0" => "INFO*KDPRODUK*MID*STEP*TANGGAL*VIA*ISIKOMPLAIN*IDOUTLET*PIN*TOKEN",
			"1" => "INFO*KDPRODUK*MID*STEP*TANGGAL*VIA*ISIKOMPLAIN*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*STATUS*KETERANGAN",
		);
		return $msg;
	}
	public static function transfer(){
		$msg = array(
			"0" => "KIRIM*KDPRODUK*MID*STEP*TANGGAL*VIA*IDTUJUAN*NOMINAL*IDOUTLET*PIN*TOKEN",
			"1" => "KIRIM*KDPRODUK*MID*STEP*TANGGAL*VIA*IDTUJUAN*NOMINAL*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*STATUS*KETERANGAN",
		);
		return $msg;
	}
	public static function daftar(){
		$msg = array(
			"0" => "DAFTAR*KDPRODUK*MID*STEP*TANGGAL*VIA*NOHP*NAMA*ALAMAT*KDPROPINSI*KOTA*KODEPOS*TIPELOKET*FLAGREGIONAL*IDOUTLET*PIN*TOKEN",
			"1" => "DAFTAR*KDPRODUK*MID*STEP*TANGGAL*VIA*NOHP*NAMA*ALAMAT*KDPROPINSI*KOTA*KODEPOS*TIPELOKET*FLAGREGIONAL*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*IDOUTLETBARU*PINBARU*STATUS*KETERANGAN",
		);
		return $msg;
	}
	public static function cekHarga(){
		$msg = array(
			"0" => "HARGA*KDPRODUK*MID*STEP*TANGGAL*VIA*OPERATORPULSA*IDOUTLET*PIN*TOKEN",
			"1" => "HARGA*KDPRODUK*MID*STEP*TANGGAL*VIA*OPERATORPULSA*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*STATUS*KETERANGAN",
		);
		return $msg;
	}
	public static function updateMenu(){
		$msg = array(
			"0" => "MENU*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN",
			"1" => "MENU*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN*SALDO*IDTRX*STATUS*KETERANGAN*MENU_PRODUK_PULSA*MENU_PRODUK_PAYMENT",
		);
		return $msg;
	}
	public static function customAdmin(){
		$msg = array(
			"0" => "SETFEE*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN*KODEPRODUK_1:FEEPRODUK_1#KODEPRODUK_2:FEEPRODUK_2#KODEPRODUK_3:FEEPRODUK_3#KODEPRODUK_4:FEEPRODUK_4",
			"1" => "SETFEE*KDPRODUK*MID*STEP*TANGGAL*VIA*IDOUTLET*PIN*TOKEN*KODEPRODUK_1:FEEPRODUK_1#KODEPRODUK_2:FEEPRODUK_2#KODEPRODUK_3:FEEPRODUK_3#KODEPRODUK_4:FEEPRODUK_4*SALDO*IDTRX*STATUS*KETERANGAN"
		);
		return $msg;
	}

	public static function pulsa(){
		$msg = array(
			"0" => "PULSA*KDPRODUK*MID*STEP*TANGGAL*VIA*NOHP*NOMINAL*IDOUTLET*PIN*TOKEN*KODEPRODUKBILLER",
			"1" => "PULSA*KDPRODUK*MID*STEP*TANGGAL*VIA*NOHP*NOMINAL*IDOUTLET*PIN*TOKEN*KODEPRODUKBILLER*SN*SALDO*IDTRX*STATUS*KETERANGAN",
		);
		return $msg;
	}
	public static function game(){
		$msg = array(
			"0" => "GAME*KDPRODUK*MID*STEP*TANGGAL*VIA*NOHP*NOMINAL*IDOUTLET*PIN*TOKEN*KODEPRODUKBILLER",
			"1" => "GAME*KDPRODUK*MID*STEP*TANGGAL*VIA*NOHP*NOMINAL*IDOUTLET*PIN*TOKEN*KODEPRODUKBILLER*SN*SALDO*IDTRX*STATUS*KETERANGAN",
		);
		return $msg;
	}
	public static function mandatoryPayment(){
		$msg = array(
			"inq" => "TAGIHAN*KDPRODUK*MID*STEP*TANGGAL*VIA*IDPEL1*IDPEL2*IDPEL3*NOMINAL*NOMINALADMIN*IDOUTLET*PIN*TOKEN*SALDO*JENISSTRUK*KODEBANK*KODEPRODUKBILLER*IDTRX*STATUS*KETERANGAN",
			"pay" => "BAYAR*KDPRODUK*MID*STEP*TANGGAL*VIA*IDPEL1*IDPEL2*IDPEL3*NOMINAL*NOMINALADMIN*IDOUTLET*PIN*TOKEN*SALDO*JENISSTRUK*KODEBANK*KODEPRODUKBILLER*IDTRX*STATUS*KETERANGAN",
			"cetak" => "CU*KDPRODUK*MID*STEP*TANGGAL*VIA*IDPEL1*IDPEL2*IDPEL3*NOMINAL*NOMINALADMIN*IDOUTLET*PIN*TOKEN*SALDO*JENISSTRUK*KODEBANK*KODEPRODUKBILLER*IDTRX*STATUS*KETERANGAN",
		);
		return $msg;
	}
	
	public static function telkom(){
		$msg = "KODEAREA*NOMORTELEPON*KODEDIVRE*KODEDATEL*JUMLAHBILL*NOMORREFERENSI3*NILAITAGIHAN3*NOMORREFERENSI2*NILAITAGIHAN2*NOMORREFERENSI1*NILAITAGIHAN1*NAMAPELANGGAN*NPWP";
		return $msg;
	}

	public static function opendenom(){
		$msg = "CUSTOMERNAME*AMOUNT*REFNO*REFNO2*BILLERCODE*BILLERSTAN*FEEAMOUNT*MERCHANTID*MERCHANTNAME*MERCHANTTYPE*ADDTDATA*ADDTDATA2*FORWARDINGID*TERMINALID*ISSUERID*TRXCODE*POSENTRYMOD*SETTLEMENTDATE*CAPTUREDATE*APPROVALCODE*ACCNO";
		return $msg;
	}
	
	public static function plnPasca(){
		$msg = "SWITCHERID*SUBSCRIBERID*BILLSTATUS*PAYMENTSTATUS*TOTALOUTSTANDINGBILL*SWREFERENCENUMBER*SUBSCRIBERNAME*SERVICEUNIT*SERVICEUNITPHONE*SUBSCRIBERSEGMENTATION*POWERCONSUMINGCATEGORY*TOTALADMINCHARGE*BLTH1*DUEDATE1*METERREADDATE1*RPTAG1*INCENTIVE1*VALUEADDEDTAX1*PENALTYFEE1*SLALWBP1*SAHLWBP1*SLAWBP1*SAHWBP1*SLAKVARH1*SAHKVARH1*BLTH2*DUEDATE2*METERREADDATE2*RPTAG2*INCENTIVE2*VALUEADDEDTAX2*PENALTYFEE2*SLALWBP2*SAHLWBP2*SLAWBP2*SAHWBP2*SLAKVARH2*SAHKVARH2*BLTH3*DUEDATE3*METERREADDATE3*RPTAG3*INCENTIVE3*VALUEADDEDTAX3*PENALTYFEE3*SLALWBP3*SAHLWBP3*SLAWBP3*SAHWBP3*SLAKVARH3*SAHKVARH3*BLTH4*DUEDATE4*METERREADDATE4*RPTAG4*INCENTIVE4*VALUEADDEDTAX4*PENALTYFEE4*SLALWBP4*SAHLWBP4*SLAWBP4*SAHWBP4*SLAKVARH4*SAHKVARH4*ALAMAT*PLNNPWP*SUBSCRIBERNPWP*TOTALRPTAG*INFOTEKS";
		return $msg;
	}
	
	public static function plnPra(){
		$msg = "SWITCHERID*NOMORMETER*IDPELANGGAN*FLAG*NOREF1*NOREF2*VENDINGRECEIPTNUMBER*NAMAPELANGGAN*SUBSCRIBERSEGMENTATION*POWERCONSUMINGCATEGORY*MINORUNITOFADMINCHARGE*ADMINCHARGE*BUYINGOPTION*DISTRIBUTIONCODE*SERVICEUNIT*SERVICEUNITPHONE*MAXKWHLIMIT*TOTALREPEATUNSOLDTOKEN*UNSOLD1*UNSOLD2*TOKENPLN*MINORUNITSTAMPDUTY*STAMPDUTY*MINORUNITPPN*PPN*MINORUNITPPJ*PPJ*MINORUNITCUSTOMERPAYABLESINSTALLMENT*CUSTOMERPAYABLESINSTALLMENT*MINORUNITOFPOWERPURCHASE*POWERPURCHASE*MINORUNITOFPURCHASEDKWHUNIT*PURCHASEDKWHUNIT*INFOTEXT";
		return $msg;
	}
	
	public static function plnNon(){
		$msg = "SWITCHERID*REGISTRATIONNUMBER*AREACODE*TRANSACTIONCODE*TRANSACTIONNAME*REGISTRATIONDATE*EXPIRATIONDATE*SUBSCRIBERID*SUBSCRIBERNAME*PLNREFNUMBER*SWREFNUMBER*SERVICEUNIT*SERVICEUNITADDRESS*SERVICEUNITPHONE*TOTALTRANSACTIONAMOUNTMINOR*TOTALTRANSACTIONAMOUNT*PLNBILLMINORUNIT*PLNBILLVALUE*ADMINCHARGEMINORUNIT*ADMINCHARGE*MUTATIONNUMBER*SUBSCRIBERSEGMENTATION*POWERCONSUMINGCATEGORY*TOTALREPEAT*CUSTOMERDETAILCODE1*CUSTOMDETAILMINORUNIT1*CUSTOMDETAILVALUEAMOUNT1*CUSTOMERDETAILCODE2*CUSTOMDETAILMINORUNIT2*CUSTOMDETAILVALUEAMOUNT2*INFOTEXT";
		return $msg;
	}
	
	public static function tvKabel(){
		$msg = "SWITCHERID*BILLERCODE*CUSTOMERID*BILLQUANTITY*NOREF1*NOREF2*CUSTOMERNAME*CUSTOMERADDRESS*PRODUCTCATEGORY*BILLAMOUNT*PENALTY*STAMPDUTY*PPN*ADMINCHARGE*BILLERREFNUMBER*PTNAME*BILLERADMINFEE*MISCFEE*MISCNUMBER*PERIODE*DUEDATE*CUSTOMINFO1*CUSTOMINFO2*CUSTOMINFO3";
		return $msg;
	}

	public static function multiFinance(){
		$msg = "SWITCHERID*BILLERCODE*CUSTOMERID*BILLQUANTITY*NOREF1*NOREF2*CUSTOMERNAME*PRODUCTCATEGORY*MINORUNIT*BILLAMOUNT*STAMPDUTY*PPN*ADMINCHARGE*BILLERREFNUMBER*PTNAME*BRANCHNAME*ITEMMERKTYPE*CHASISNUMBER*CARNUMBER*TENOR*LASTPAIDPERIODE*LASTPAIDDUEDATE*MINORUNIT*OSINSTALLMENTAMOUNT*ODINSTALLMENTPERIOD*ODINSTALLMENTAMOUNT*ODPENALTYFEE*BILLERADMINFEE*MISCFEE*MINIMUMPAYAMOUNT*MAXIMUMPAYAMOUNT";
		return $msg;
	}	
	
	public static function kartuKredit(){
		$msg = "SWITCHERID*BILLERCODE*CUSTOMERID*BILLQUANTITY*NOREF1*NOREF2*CUSTOMERNAME*PRODUCTCATEGORY*BILLAMOUNT*PENALTY*STAMPDUTY*PPN*ADMINCHARGE*BILLERREFNUMBER*PTNAME*LASTPAIDPERIODE*LASTPAIDDUEDATE*BILLERADMINFEE*MISCFEE*MISCNUMBER*MINIMUMPAYAMOUNT*MAXIMUMPAYAMOUNT";
		return $msg;
	}
	
	public static function asuransi(){
		$msg = "SWITCHERID*BILLERCODE*CUSTOMERID*BILLQUANTITY*NOREF1*NOREF2*CUSTOMERNAME*PRODUCTCATEGORY*BILLAMOUNT*PENALTY*STAMPDUTY*PPN*ADMINCHARGE*CLAIMAMOUNT*BILLERREFNUMBER*PTNAME*LASTPAIDPERIODE*LASTPAIDDUEDATE*BILLERADMINFEE*MISCFEE*MISCNUMBER*CUSTOMERPHONENUMBER*CUSTOMERADDRESS*AHLIWARISPHONENUMBER*AHLIWARISADDRESS";
		return $msg;
	}
	
	public static function pdam(){
		$msg = "SWITCHERID*BILLERCODE*CUSTOMERID1*CUSTOMERID2*CUSTOMERID3*BILLQUANTITY*NOREF1*NOREF2*CUSTOMERNAME*CUSTOMERADDRESS*CUSTOMERDETAILINFORMATION*BILLERADMINCHARGE*TOTALBILLAMOUNT*PDAMNAME*MONTHPERIOD1*YEARPERIOD1*FIRSTMETERREAD1*LASTMETERREAD1*PENALTY1*BILLAMOUNT1*MISCAMOUNT1*MONTHPERIOD2*YEARPERIOD2*FIRSTMETERREAD2*LASTMETERREAD2*PENALTY2*BILLAMOUNT2*MISCAMOUNT2*MONTHPERIOD3*YEARPERIOD3*FIRSTMETERREAD3*LASTMETERREAD3*PENALTY3*BILLAMOUNT3*MISCAMOUNT3*MONTHPERIOD4*YEARPERIOD4*FIRSTMETERREAD4*LASTMETERREAD4*PENALTY4*BILLAMOUNT4*MISCAMOUNT4*MONTHPERIOD5*YEARPERIOD5*FIRSTMETERREAD5*LASTMETERREAD5*PENALTY5*BILLAMOUNT5*MISCAMOUNT5*MONTHPERIOD6*YEARPERIOD6*FIRSTMETERREAD6*LASTMETERREAD6*PENALTY6*BILLAMOUNT6*MISCAMOUNT6";
		return $msg;
	}
	
	public static function delima(){
		$msg = "IDENTITASPENERIMA*KODETRANSFER*AMOUNT*ADMINFEE*NOREF*NAMAPENGIRIM*JENISKELAMINPENGIRIM*ALAMATPENGIRIM*KOTAPENGIRIM*KODEPOSPENGIRIM*NEGARAPENGIRIM*TIPEIDCARDPENGIRIM*NOMORIDCARDPENGIRIM*TEMPATLAHIRPENGIRIM*TANGGALLAHIRPENGIRIM*NOMORTELEPONPENGIRIM*NAMAPENERIMA*JENISKELAMINPENERIMA*ALAMATPENERIMA*KOTAPENERIMA*KODEPOSPENERIMA*NEGARAPENERIMA*TIPEIDCARDPENERIMA*NOMORIDCARDPENERIMA*TEMPATLAHIRPENERIMA*TANGGALLAHIRPENERIMA*NOMORTELEPONPENERIMA";
		return $msg;
	}
	
	public static function teleponPasc(){
		$msg = "SWITCHERID*BILLERCODE*CUSTOMERID*BILLQUANTITY*NOREF1*NOREF2*CUSTOMERNAME*CUSTOMERADDRESS*BILLERADMINCHARGE*TOTALBILLAMOUNT*PROVIDERNAME*MONTHPERIOD1*YEARPERIOD1*PENALTY1*BILLAMOUNT1*MISCAMOUNT1*MONTHPERIOD2*YEARPERIOD2*PENALTY2*BILLAMOUNT2*MISCAMOUNT2*MONTHPERIOD3*YEARPERIOD3*PENALTY3*BILLAMOUNT3*MISCAMOUNT3";
		return $msg;
	}
        
        public static function dataTransaksi(){
		$msg = "TANGGAL1*TANGGAL2*KDPRODUK*IDPEL*LIMIT*IDOUTLET*PIN*RESPONSECODE*CONTENT";
		return $msg;
	}
        public static function statusTransaksi(){
		$msg = "IDTRX*IDPEL*IDOUTLET*PIN*RESPONSECODE*CONTENT";
		return $msg;
	}
    public static function newPdam(){
		$msg = "SWITCHERID*CUSTOMERID1*CUSTOMERID2*CUSTOMERID3*BILLQUANTITY*GWREFNUM*SWREFNUM*CUSTOMERNAME*CUSTOMERADDRESS*CUSTOMERSEGMENTATION*CUSTOMERDETAILINFORMATION*BILLERADMINCHARGE*TOTALBILLAMOUNT*PDAMNAME*STAMPDUTY*TRANSACTIONFEE*OTHERFEE*MONTHPERIOD1*YEARPERIOD1*METERUSAGE1*STAND1*FIRSTMETERREAD1*LASTMETERREAD1*BILLAMOUNT1*PENALTY1*BURDENAMOUNT1*MISCAMOUNT1*MONTHPERIOD2*YEARPERIOD2*METERUSAGE2*STAND2*FIRSTMETERREAD2*LASTMETERREAD2*BILLAMOUNT2*PENALTY2*BURDENAMOUNT2*MISCAMOUNT2*MONTHPERIOD3*YEARPERIOD3*METERUSAGE3*STAND3*FIRSTMETERREAD3*LASTMETERREAD3*BILLAMOUNT3*PENALTY3*BURDENAMOUNT3*MISCAMOUNT3*MONTHPERIOD4*YEARPERIOD4*METERUSAGE4*STAND4*FIRSTMETERREAD4*LASTMETERREAD4*BILLAMOUNT4*PENALTY4*BURDENAMOUNT4*MISCAMOUNT4*MONTHPERIOD5*YEARPERIOD5*METERUSAGE5*STAND5*FIRSTMETERREAD5*LASTMETERREAD5*BILLAMOUNT5*PENALTY5*BURDENAMOUNT5*MISCAMOUNT5*MONTHPERIOD6*YEARPERIOD6*METERUSAGE6*STAND6*FIRSTMETERREAD6*LASTMETERREAD6*BILLAMOUNT6*PENALTY6*BURDENAMOUNT6*MISCAMOUNT6";
		return $msg;
	}

	public static function newAsuransi(){
		$msg = "SWITCHERID*BILLER_CODE*CUSTOMER_ID*BILL_QUANTITY*NOREF1*NOREF2*CUSTOMER_NAME*PRODUCT_CATEGORY*BILL_AMOUNT*PENALTY*STAMP_DUTY*PPN*ADMIN_CHARGE*CLAIM_AMOUNT*BILLER_REF_NUMBER*PT_NAME*LAST_PAID_PERIODE*LAST_PAID_DUE_DATE*BILLER_ADMIN_FEE*MISC_FEE*MISC_NUMBER*POLICY_NUMBER*CUSTOMER_PHONE_NUMBER*CUSTOMER_ADDRESS*CUSTOMER_GENDER*CUSTOMER_JOB*BENEFICIARY_NAME*BENEFICIARY_PHONE_NUMBER*BENEFICIARY_ADDRESS*BENEFICIARY_RELATION*REGISTRATION_DATE*START_DATE*END_DATE*INFO_TEKS";
		return $msg;
	}

	public static function bpjs(){
		$msg = "CMD*NIK*CUSTOMER_NAME*TANGGAL_LAHIR*KODE_BAYAR*FTRXID*DATA1*DATA2*DATA3*DATA4*TAGIHAN*ADMIN*KPJ*PEKERJAAN*JAM_AWAL*JAM_AKHIR*ALAMAT*ALAMAT_EMAIL*LOKASI_KERJA*UPAH*KEC*KEL*KODEPOS*HP*OTP*JHT*RATE_JHT*JKK*RATE_JKK*JKM*RATE_JKM*ISNEW*STATUS_BAYAR*BIAYA_REGISTRASI*KODE_KANTOR_CABANG*ALAMAT_KANTOR_CABANG*KODE_KABUPATEN*KODE_PROVINSI*PROGRAM*PERIODE*STATUS_HITUNG_IURAN*BLN_JKM*BLN_JKK*BLN_JHT*KET1*KET2*KET3";
		return $msg;
	}

	public static function pgn(){
		$msg = "CUSTOMERID*CUSTOMERNAME*USAGE*PERIODE*INVOICENUMBER*TAGIHAN*ADMINBANK*TOTAL*CHARGE*SALDORET*REFFID*TRXID";
		return $msg;
	}

	public static function gas(){
		$msg = "SWITCHERID*BILLERCODE*CUSTOMERID1*CUSTOMERID2*CUSTOMERID3*BILLQUANTITY*GWREFNUM*SWREFNUM*CUSTOMERNAME*CUSTOMERADDRESS*CUSTOMERDETAILINFORMATION*BILLERADMINCHARGE*TOTALBILLAMOUNT*PDAMNAME*MONTHPERIOD1*YEARPERIOD1*FIRSTMETERREAD1*LASTMETERREAD1*PENALTY1*BILLAMOUNT1*MISCAMOUNT1*MONTHPERIOD2*YEARPERIOD2*FIRSTMETERREAD2*LASTMETERREAD2*PENALTY2*BILLAMOUNT2*MISCAMOUNT2*MONTHPERIOD3*YEARPERIOD3*FIRSTMETERREAD3*LASTMETERREAD3*PENALTY3*BILLAMOUNT3*MISCAMOUNT3*MONTHPERIOD4*YEARPERIOD4*FIRSTMETERREAD4*LASTMETERREAD4*PENALTY4*BILLAMOUNT4*MISCAMOUNT4*MONTHPERIOD5*YEARPERIOD5*FIRSTMETERREAD5*LASTMETERREAD5*PENALTY5*BILLAMOUNT5*MISCAMOUNT5*MONTHPERIOD6*YEARPERIOD6*FIRSTMETERREAD6*LASTMETERREAD6*PENALTY6*BILLAMOUNT6*MISCAMOUNT6";
		return $msg;
	}
	public static function lakupandai()
	{
		$msg = "CMD*DEALERID*SYSTEMID*ACCOUNTNUM*OPTION*IDAGEN*CURRENCY*ACCOUNT_STATUS*PRODUCT*HOMEBRANCH*CIFNUM*NAME*NAMEREK*CURRENTBALANCE*AVAILABLEBALANCE*OPENDATE*ADDRESS_STREET*ADDRESS_RT*ADDRESS1*ADDRESS2*ADDRESS3*ADDRESS4*POSTCODE*HOMEPHONE*FAX*OFFICEPHONE*MOBILEPHONE*ADDRESS1AA*ADDRESS2AA*ADDRESS3AA*ADDRESS4AA*POSTCODEAA*ACCOUNTPRODUCTTYPE*ACCTYPE*SUBCAT*AVAILABLEINTEREST*LIENBALANCE*UNCLEARBALANCE*INTERESTRATE*KTP*NPWP*JENIS_PEKERJAAN*EMAIL*KODE_WIL_BI*KODE_CABANG*KODE_LOKET*KODE_MITRA*TGL_INPUT*CA_GEN_STATUS*CLIENTID*CLIENT_ACCOUNT_NUM*REQ_ID*REQ_TIME*CUST_ACC_NUM*AMOUNT*TRANSACTION_JOURNAL*CUSTOMER_OTP*CUST_FIRST_NAME*CUST_MIDLE_NAME*CUST_LAST_NAME*CUST_PLACE_OF_BIRTH*CUST_DATE_OF_BIRTH*CUST_GENDER*CUST_IS_MARRIED*CUST_INCOME*PIN_TRANSAKSI*IMAGE_NAME*IMAGE_URL*FILE_NAME*IMAGE_FOTO_NAME*IMAGE_FOTO_URL*FILE_NAME_FOTO";
		return $msg;
	}
}
?>
